import { BarcodeType } from './types';

export const BARCODE_DEFAULT_WIDE = {
  [BarcodeType.Code128]: 1,
  [BarcodeType.Code128M]: 1,
  [BarcodeType.EAN128]: 1,
  [BarcodeType.Interleaved2Of5]: 3,
  [BarcodeType.Interleaved2Of5C]: 3,
  [BarcodeType.Code39]: 3,
  [BarcodeType.Code39C]: 3,
  [BarcodeType.Code93]: 3,
  [BarcodeType.EAN13]: 1,
  [BarcodeType.EAN13Plus2]: 1,
  [BarcodeType.EAN13Plus5]: 1,
  [BarcodeType.EAN8]: 1,
  [BarcodeType.EAN8Plus2]: 1,
  [BarcodeType.EAN8Plus5]: 1,
  [BarcodeType.Codabar]: 3,
  [BarcodeType.Postnet]: 1,
  [BarcodeType.UPCA]: 1,
  [BarcodeType.UPCA2]: 1,
  [BarcodeType.UPA5]: 1,
  [BarcodeType.UPCE]: 1,
  [BarcodeType.UPCE2]: 1,
  [BarcodeType.UPE5]: 1,
  [BarcodeType.CPOST]: 7,
  [BarcodeType.MSI]: 3,
  [BarcodeType.MSIC]: 3,
  [BarcodeType.Plessey]: 3,
  [BarcodeType.ITF14]: 3,
  [BarcodeType.EAN14]: 1,
  [BarcodeType.Code11]: 3,
};

export const STATUS_MAP: Record<string, string> = {
  '\x00': 'Normal',
  '\x01': 'Head opened',
  '\x02': 'Paper Jam',
  '\x03': 'Paper Jam and head opened',
  '\x04': 'Out of paper',
  '\x05': 'Out of paper and head opened',
  '\x08': 'Out of ribbon',
  '\x09': 'Out of ribbon and head opened',
  '\x0A': 'Out of ribbon and paper jam',
  '\x0B': 'Out of ribbon, paper jam and head opened',
  '\x0C': 'Out of ribbon and out of paper',
  '\x0D': 'Out of ribbon, out of paper and head opened',
  '\x10': 'Pause',
  '\x20': 'Printing',
  '\x80': 'Other error',
};
