import { BarcodeType } from './types';

export const BARCODE_DEFAULT_WIDE = {
  [BarcodeType.Code128]: 1,
  [BarcodeType.Code128M]: 1,
  [BarcodeType.EAN128]: 1,
  [BarcodeType.Interleaved2Of5]: 3,
  [BarcodeType.Interleaved2Of5C]: 3,
  [BarcodeType.Code39]: 3,
  [BarcodeType.Code39C]: 3,
  [BarcodeType.Code93]: 3,
  [BarcodeType.EAN13]: 1,
  [BarcodeType.EAN13Plus2]: 1,
  [BarcodeType.EAN13Plus5]: 1,
  [BarcodeType.EAN8]: 1,
  [BarcodeType.EAN8Plus2]: 1,
  [BarcodeType.EAN8Plus5]: 1,
  [BarcodeType.Codabar]: 3,
  [BarcodeType.Postnet]: 1,
  [BarcodeType.UPCA]: 1,
  [BarcodeType.UPCA2]: 1,
  [BarcodeType.UPA5]: 1,
  [BarcodeType.UPCE]: 1,
  [BarcodeType.UPCE2]: 1,
  [BarcodeType.UPE5]: 1,
  [BarcodeType.CPOST]: 7,
  [BarcodeType.MSI]: 3,
  [BarcodeType.MSIC]: 3,
  [BarcodeType.Plessey]: 3,
  [BarcodeType.ITF14]: 3,
  [BarcodeType.EAN14]: 1,
  [BarcodeType.Code11]: 3,
};
